### ISSUE TITLE
char2idx.pickle is not included in the directory

### ISSUE THREAD

**Issue by EvanSamaa** [schufo/plla-tisvs#1]
The char2idx.pickle, which is used in 03_preprocessing_musdb_audio_txt_char.py is missing. It is neither found on git or the provided links. It would be super kind of you to provide it! thank you!

**Comment by schufo** [comment]
Hi! Thanks a lot for pointing this out. I added the file in the 'dicts' folder and updated the path in the script. Don't hesitate to open a new issue if something else does not work. Cheers!

**Comment by EvanSamaa** [comment]
Thank you so much! Also, that paper was excellent, it was well written and I'm super impressed with the creative approach! Keep up the good work!

**Comment by schufo** [comment]
That's good to hear, thanks!
